backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
media_folder: static/uploads
public_folder: /uploads

collections:
  - name: "hook"
    label: "Hook"
    folder: "content/hooks"
    create: true
    fields:
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
