name: Export

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  export:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Setup
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and Build 🔧
      - run: |
          yarn install
          yarn generate

      - name: Deploy 🚀
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: public
          FOLDER: ./dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
